### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Jig5aw12** [xpboosting/8-Ball-Pool-Cheto#1]
Idk why but for me it doesn't work, exactly the loader it doesn't start, it gives me curl error and I don't have a Linux machine

**Comment by xpboosting** [comment]
> Idk why but for me it doesn't work, exactly the loader it doesn't start, it gives me curl error and I don't have a Linux machine

can you send me a screenshot with error?

**Comment by Jig5aw12** [comment]
Cannot open curl.h, and json.cpp, I will send you ss in a moment, do u have
discord? If yes add me:   1339#9512 and let's talk there.

**Comment by Jig5aw12** [comment]
> > Idk why but for me it doesn't work, exactly the loader it doesn't start, it gives me curl error and I don't have a Linux machine
> 
> can you send me a screenshot with error?

Add me on dis, it is easy there 1339#9512
